### ISSUE TITLE
Ambiguous event extension description

### ISSUE THREAD

**Issue by nicholasruunu** [icicleio/icicle#10]
This part of the documentation is very confusing. Which one is more performant?
- event extension: Allows for the most performant event loop implementation.
- libevent extension: Similar to the event extension, it allows for a more performant event loop implementation.

**Comment by trowski** [comment]
They are about the same actually, with perhaps a slight preference toward event. I plan on adding one or two more loop implementations in the near future and will make this clearer then.

**Comment by trowski** [comment]
An event loop implementation supporting the ev extension has been added and is now the preferred extension for the event loop. The section suggesting extensions has also been updated to clarify which extension is preferred. Thanks for pointing this out!
