### ISSUE TITLE
Fix PHP requirement in the Readme

### ISSUE THREAD

**Issue by Revisor** [icicleio/icicle#11]
The Readme says PHP 5.5.+, the real requirement is PHP 7.0+.

**Comment by trowski** [comment]
The `master` branch is PHP 7.0+. There are also `v0.8.x` and `v1.x` branches that are PHP 5.5+. My intention is to release v1.0 supporting PHP 5.5+ and shortly after release a similar v2.0 requiring PHP 7 that takes advantage of 7's new generator features.

The Readme should be updated to make this clearer, as it is confusing when looking at the source that PHP 5.5+ is supported.

**Comment by GrahamCampbell** [comment]
I think the readme for each branch should reflect the version of php on that branch.

**Comment by GrahamCampbell** [comment]
Maybe it's worth changing the default branch from master?

**Comment by trowski** [comment]
Changing the default branch for now might be a good idea. I would like people to be immediately aware of both versions, so eventually I would like the default branch to make note of both. Otherwise in general I agree with @GrahamCampbell that the readme should reflect the branch that it is on.

**Comment by Revisor** [comment]
Ah, I see and thanks for your replies.

In that case from my point of view the best solution would be to explain the two branches in the Readme.
And maybe rename the branches so that they reflect the difference?

Subquestion: Are you not going to follow semantic versioning? Composer really amplifies the usefulness of semver.

**Comment by trowski** [comment]
Icicle definitely plans to follow semver, which is why the the 7.0+ only version will be v2.0, as it has some BC breaks (though fairly minor) to take better advantage of some of PHP 7's new generator features.

@Revisor Is there any issue you see with this plan and semver compliance?

**Comment by Revisor** [comment]
What happens when either of those two versions needs a BC break (for example any change in an interface) and this bumps up the major version? Do they use v3.0? I can imagine it could get very confusing pretty quickly.

What do you think about splitting both versions into their separate repositories/projects with their own versioning, i.e. Icicle v1.0, Icicle-php5 v1.0? (Icicle for PHP7 being the default, without a version note, since that's where the community will move in the future).

**Comment by deviantmk** [comment]
+1 looks pretty reasonable

**Comment by sagebind** [comment]
After some internal discussion, we have decided that we will release the PHP 5-compatible version as 1.0, and the PHP7-compatible version as 2.0. As we plan to drop PHP 5 support in future iterations of Icicle, version 1.x will be the only stable version that supports PHP 5. Major changes that would introduce BC breaks will be for version 2.x and onward and future development will focus on PHP7. 

Some improvements will be backported to 1.x as they are developed, and all security patches will be backported for the lifetime of the version. 1.x will likely be supported for the entire lifetime of PHP 5.6, and phased out when PHP 5.6 is no longer supported by the PHP group.

We will update the README and the documentation to reflect this decision and make it more clear what versions are available.

**Comment by Revisor** [comment]
Thank you for considering it. This solution sounds reasonable.
