### ISSUE TITLE
SocketEvent raise exception for fd resource

### ISSUE THREAD

**Issue by goddanao** [icicleio/icicle#13]
The constructor of Icicle\Loop\Events\SocketEvent throws an Exception when $resource is an fd (int).
This error emerged whlle testing your react/loop integration with zeromq.

**Comment by sagebind** [comment]
Thanks for reporting the issue (and for being interested in Icicle)! What version of Icicle are you using?

**Comment by goddanao** [comment]
icicleio/icicle v0.8.3
icicleio/react-adapter v0.3.1
react/event-loop v0.4.1

**Comment by sagebind** [comment]
Okay thanks. Can you give some code that generates this error? When adding a stream to the event loop, it should only throw an exception if `$resource` is an invalid resource handle.

**Comment by goddanao** [comment]
Icicle\ReactAdapter\Loop::addReadStream use

**Comment by goddanao** [comment]
I'm using react/zeromq wich support polling for zeromq sockets. Those sockets are handled by react loop using the filedescriptor wich is an int [(see here)](https://github.com/reactphp/zmq/blob/master/src/SocketWrapper.php#L58).

Removing the check for $resource is an invalid resource handle allow to use filedescriptors.
I removed those lines and worked as expected.

**Comment by trowski** [comment]
I removed the `is_resource()` check in v0.9, which I'll be tagging shortly. I'll need to update the related libraries to work with the new version, as there's a number of changes in v0.9. Hopefully this will be the last major change before a v1.0.

I'll update and close this issue once everything is ready for you to try the new version.

**Comment by trowski** [comment]
@goddanao Try using the new version of Icicle and related packages with your code and see if it works now. I removed the resource check from `SocketEvent`, which has also been renamed to `Io`.

`"icicleio/icicle": "^0.9.1"`
`"icicleio/react-adaptor": "^0.4"`

Many interfaces and classes were renamed to remove `Interface` suffixes with the new versions, but you should be able to update with find-and-replace fairly quickly. If you have any questions, don't hesitate to ask.
