### ISSUE TITLE
stream_select behaviour

### ISSUE THREAD

**Issue by barrylb** [icicleio/icicle#18]
In SelectLoop.php's call to stream_select the 'read' and 'write' arrays are populated such that the array keys are the integer cast of the resource id and the values are the resource itself. Usually the output from stream_select preserves the array keys and this is passed to pollManager->handle.

However I have found the array keys are not always preserved. In my testing with a single socket the key becomes 0 instead of the integer cast of the resource id. This breaks pollManager->handle, causing it to not find the socket. I cannot explain why it only happens sometimes.

The following debugging code added to SelectLoop.php's dispatch function can detect the problem in my application:
if ($count) {
/// begin insert debugging code ///
    foreach ($read as $id => $resource) {
        if ($id != (int) $resource) {
            die("stream_select mismatch $id != $resource");
        }
    }
// end insert debugging code ////
}

The fix is to modify the 'handle' function in SelectIoManager.php.
Replacing:
foreach ($active as $id => $resource) {
...
With:
foreach ($active as $resource) {
            $id = (int) $resource;
...

**Comment by trowski** [comment]
What operating system are you using? I've never seen this behavior... maybe it's something I can patch in `stream_select()` itself. Regardless, since the fix was so simple in Icicle I did what you suggested and cast `$resource` to an `int` instead of using the array key.

**Comment by barrylb** [comment]
Thanks very much for making this change. I'm using Windows OS.
