### ISSUE TITLE
Icicle performance test

### ISSUE THREAD

**Issue by kirensiva** [icicleio/icicle#19]
I have 2 download scripts **async_downloader.php** and **downloader.php**. Both are for getting the contents from URLs.  First one is using Icicle co routine to increase the performance and the second one is a usual php loop. I have logged start time and end time of both the scripts, but there is no much performance difference I saw. Some times normal php script is faster than Icicle co routine. My codes  are given below. Please advice me if I am missing anything in the scripts.
### async_downloader.php

```
require './vendor/autoload.php';
use Icicle\Coroutine;
use Icicle\Loop;
use Icicle\Stream;
echo 'Start Time:' . date('Y-m-d H:i:s') . PHP_EOL;
Coroutine\create(function () {
    // Infinitely get input from the console until the user terminates the program.
    $i = 0;
    $url = [
        'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
        'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
        'http://github.com/icicleio',
        'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
        'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
        'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
        'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
        'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
        'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1'
    ];

    echo count($url) . PHP_EOL;
    while ($i <= count($url)) {
        // We use a new coroutine here so that the download will run independently
        // of our loop.
        Coroutine\create(function () use ($url, $i) {
            if (isset($url[$i]) && $url[$i] != '') {
                echo 'Processing ' . $url[$i] . PHP_EOL;
                $content = (yield file_get_contents($url[$i]));
                (yield file_put_contents($i . '.html', $content));
            }
        });
        $i++;
    }
});
echo 'End Time:' . date('Y-m-d H:i:s') . PHP_EOL;
// Run the event loop, as usual.
Loop\run();
```
### downloader.php

```
echo 'Start Time:' . date('Y-m-d H:i:s') . PHP_EOL;
$i = 0;
$url = [
    'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
    'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
    'http://github.com/icicleio',
    'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
    'http://stackoverflow.com/questions/21700846/how-to-write-an-awaitable-method',
    'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
    'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
    'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1',
    'http://meta.stackoverflow.com/questions/333420/documentation-update-august-29th?cb=1'
];
while ($i <= count($url)) {

    if (isset($url[$i]) && $url[$i] != '') {
        echo 'Processing ' . $url[$i] . PHP_EOL;

        $content = (file_get_contents($url[$i]));
        (file_put_contents($i . '.html', $content));
    }
    $i++;
}
echo 'End Time:' . date('Y-m-d H:i:s') . PHP_EOL;
```

**Comment by sagebind** [comment]
@kirensiva You're right, there are several things done improperly here which is causing the Icicle script to be slower and not work as expected. The first problem is at the end:

``` php
echo 'End Time:' . date('Y-m-d H:i:s') . PHP_EOL;
// Run the event loop, as usual.
Loop\run();
```

In async, all of the work happens in the `run()` event loop call, so to measure the time to run, you must put your time measurement _after_ the event loop finishes, otherwise "End time" will be printed out right away before the script hardly starts. Here is the correct way:

``` php
// Do all async work
Loop\run();

echo 'End Time:' . date('Y-m-d H:i:s') . PHP_EOL;
```

The second issue is that you _cannot_ use `file_get_contents()` and `file_put_contents()` in this way. Icicle can not force everything to be async; functions have to be written with async in mind for it to work. As such, `file_get_contents()` and `file_put_contents()` are not, and likely never will be, async functions. Since they are synchronous functions, only one can run at a time, and Icicle cannot fix that. Instead, what you need to do is find asynchronous versions of those functions to use. For file operations, we have [icicleio/filesystem](https://github.com/icicleio/filesystem) you can use.

It may help to read our [Introduction to Asynchronous Programming](https://icicle.io/docs/manual/introduction/) to get a better grasp as to why this works this way. Hope that helps.

**Comment by kirensiva** [comment]
Thank you for the clarifications. Actually I want to use this library for downloading the files from a server using php FTP  script. I have completed the pure php script, but need performance boost. As you mentioned above, I tried asynchronous version of the ftp download function (non blocking) `ftp_nb_get`, but throwing following error.

`Warning: ftp_nb_get(): Port command successful in \async_ftp_downloader.php on line 32`
`Warning: ftp_nb_get(): Opening data channel for file transfer. in \async_ftp_downloader.php on line 32`
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 36 bytes) in \async_ftp_downloader.php on line 72`

Can you please help me to solve this? Below is my script.

### async_ftp_downloader.php

```
require './vendor/autoload.php';
use Icicle\Coroutine;
use Icicle\Loop;
$start_time = 'Start Time:' . date('Y-m-d H:i:s') . PHP_EOL;
$i = 0;
$url = 5;
$ftp_server = '127.0.0.1';
$ftp_user = "test";
$ftp_pass = "test";
$remote_path = '/stats_jul1/stats';
$conn_id = ftp_connect($ftp_server) or die("Couldn't connect to $ftp_server");
// try to login
if (@ftp_login($conn_id, $ftp_user, $ftp_pass)) {

    echo "Connected as $ftp_user@$ftp_server\n";
} else {
    echo "Couldn't connect as $ftp_user\n";
}
$buff = getFileListFromFtp($conn_id, $remote_path);

Coroutine\create(function () use ($url, $i, $conn_id, $remote_path, $buff) {
    // Infinitely get input from the console until the user terminates the program.
    while ($i <= count($buff) ) {
        // We use a new coroutine here so that the download will run independently
        // of our loop.
        Coroutine\create(function () use ($url, $i, $conn_id, $remote_path, $buff) {
            if (isset($buff[$i]['file_name'])) {
                echo 'processing: ' . $remote_path . '/' . $i . '.xml' . PHP_EOL;
                $ret = (yield ftp_nb_get($conn_id, $i . '.xml', $remote_path . '/' . $buff[$i]['file_name'], FTP_BINARY));
                while ($ret == FTP_MOREDATA) {
                    $ret = (ftp_nb_continue($conn_id));
                }
                if ($ret != FTP_FINISHED) {
                    echo "There was an error downloading the file...";
                    exit(1);
                }
            }
        });
        $i++;
    }
});
// Run the event loop, as usual.
Loop\run();
ftp_close($conn_id);

echo $start_time . PHP_EOL;
$end_time = 'End Time:' . date('Y-m-d H:i:s') . PHP_EOL;
echo $end_time;
$log = $start_time . $end_time;
file_put_contents('log.txt', $log);

function getFileListFromFtp($conn_id, $directory = '.') {
    if (is_array($children = @ftp_rawlist($conn_id, $directory))) {
        $items = array();
        foreach ($children as $child) {
            $chunks = preg_split("/\s+/", $child);
            list($item['rights'], $item['number'], $item['user'], $item['group'], $item['size'], $item['month'], $item['day'], $item['time']) = $chunks;
            $item['type'] = $chunks[0]{0} === 'd' ? 'directory' : 'file';
            array_splice($chunks, 0, 8);
            $file_name = implode(" ", $chunks);
            $tmp_file_name = $directory . '/' . $file_name;
            $item['file_name'] = $file_name;
            $items[] = $item;
        }

        return $items;
    } else {
        throw new Exception("Unable to get the file list from ftp.");
    }
}
```

**Comment by sagebind** [comment]
@kirensiva `ftp_nb_get()` is non-blocking, but it is not asynchronous. Icicle-compatible asynchronous functions either return an `Icicle\Awaitable\Awaitable` or a `Generator`. There are no built-in functions or functions in any extensions that I'm aware of that do this. Generally the only compatible functions at the moment can be found in other Icicle packages, which are [on Packagist in the `icicleio/` namespace](https://packagist.org/search/?q=icicleio%2F).

This is a limitation that will be somewhat solved when the [async PHP standards](https://github.com/async-interop) are ready and begin to be adopted.
